### PR TITLE
Fix bugs

### LINKED ISSUE #10: Add version and download badges to readme

### LINKED ISSUE #12: 400 bad request when calling validate on specific text
Call `validate('Willoughby Hedge')` and you'll get a 400 bad request from `file_get_contents()`. Change it to `validate('Willoughby hedge')` and you'll get back the expected response object with result `false`.

When I used Postman directly to call the API, both worked:

`https://api.postcodes.io/postcodes/Willoughby Hedge/validate`:

```
{
    "status": 200,
    "result": false
}
```

`https://api.postcodes.io/postcodes/Willoughby hedge/validate`

```
{
    "status": 200,
    "result": false
}
```

This issue can be reproduced outside of the library:

```
$ php -r "echo file_get_contents('https://api.postcodes.io/postcodes/Willoughby Hedge/validate');"

PHP Warning:  file_get_contents(https://api.postcodes.io/postcodes/Willoughby Hedge/validate): Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 in Command line code on line 1
PHP Stack trace:
PHP   1. {main}() Command line code:0
PHP   2. file_get_contents($filename = 'https://api.postcodes.io/postcodes/Willoughby Hedge/validate') Command line code:1

$ php -r "echo file_get_contents('https://api.postcodes.io/postcodes/Willoughby hedge/validate');"
{"status":200,"result":false}
```

If you urlencode the space, the problem is resolved:

```
$ php -r "echo file_get_contents('https://api.postcodes.io/postcodes/Willoughby%20Hedge/validate');"
{"status":200,"result":false}
```

Also, if your postcode contains a slash `/` the request fails, so this should be urlencoded too (`rawurlencode`).

PHP 8.1.0

### LINKED ISSUE #14: Possibly incorrect parameter order
I think random should be after %s here?

https://github.com/jabranr/postcodes-io/blob/ddfaa36bcba1f36fc48d4740d2e8a14d689ccd9d/src/PostcodesIO.php#L41

### LINKED ISSUE #16: Extend PHP support, update phpunit to latest
- [x] Deprecate older PHP support
- [x] Extend support to PHP 7.3+
- [x] Update `phpunit/phpunit`

This may introduce some new things for tests and in the existing API, this library exposes. However, I plan to keep any API changes from a minimum to none.

### LINKED ISSUE #17: Fix Bulk Reverse Geocoding API
Fix Bulk Reverse Geocoding API so it can pass a named associated array to Postcodes.io.

**Docs Reference**
- https://postcodes.io/docs#Bulk-Geocode-Postcode

Also, update the API so it can accept a named associated array in the payload.

**Currently**
```php
$payload = [
  ["123", "-321"], 
  ["456", "-978"]
]
```

**Expected**
In addition to the above, API from this library should also expect the following format.
```php
$payload = [
  ["latitude" => "123", "longitude" => "-321"], 
  ["latitude" => "456", "longitude" => "-978"]
]
```

> **Keep the changes backwards compatible**

### PR DESCRIPTION
**Pull request by jabranr**
resolves #12  #14

### CODE REVIEW

**Comment by jabranr** [comment]
@jamieburchell I have added more tests including the bug you reported. I have also extended the PHP support for it from 7.3 to 8 LTS. More in #16

**Comment by jabranr** [comment]
Resolves #17

**Comment by jabranr** [comment]
Summary of this release in the milestone v2.0.0 now at https://github.com/jabranr/postcodes-io/milestone/2

**Comment by jamieburchell** [comment]
Thanks @jabranr !

**Pull request merged**
